// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import { describe, it } from 'mocha';
import * as animeserviceModule from '../src';

import {PassThrough} from 'stream';

import {protobuf, LROperation, operationsProtos} from 'google-gax';

function generateSampleMessage<T extends object>(instance: T) {
    const filledObject = (instance.constructor as typeof protobuf.Message)
        .toObject(instance as protobuf.Message<T>, {defaults: true});
    return (instance.constructor as typeof protobuf.Message).fromObject(filledObject) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().rejects(error) : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().callsArgWith(2, error) : sinon.stub().callsArgWith(2, null, response);
}

function stubLongRunningCall<ResponseType>(response?: ResponseType, callError?: Error, lroError?: Error) {
    const innerStub = lroError ? sinon.stub().rejects(lroError) : sinon.stub().resolves([response]);
    const mockOperation = {
        promise: innerStub,
    };
    return callError ? sinon.stub().rejects(callError) : sinon.stub().resolves([mockOperation]);
}

function stubLongRunningCallWithCallback<ResponseType>(response?: ResponseType, callError?: Error, lroError?: Error) {
    const innerStub = lroError ? sinon.stub().rejects(lroError) : sinon.stub().resolves([response]);
    const mockOperation = {
        promise: innerStub,
    };
    return callError ? sinon.stub().callsArgWith(2, callError) : sinon.stub().callsArgWith(2, null, mockOperation);
}

function stubPageStreamingCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    const pagingStub = sinon.stub();
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
        }
    }
    const transformStub = error ? sinon.stub().callsArgWith(2, error) : pagingStub;
    const mockStream = new PassThrough({
        objectMode: true,
        transform: transformStub,
    });
    // trigger as many responses as needed
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            setImmediate(() => { mockStream.write({}); });
        }
        setImmediate(() => { mockStream.end(); });
    } else {
        setImmediate(() => { mockStream.write({}); });
        setImmediate(() => { mockStream.end(); });
    }
    return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    let counter = 0;
    const asyncIterable = {
        [Symbol.asyncIterator]() {
            return {
                async next() {
                    if (error) {
                        return Promise.reject(error);
                    }
                    if (counter >= responses!.length) {
                        return Promise.resolve({done: true, value: undefined});
                    }
                    return Promise.resolve({done: false, value: responses![counter++]});
                }
            };
        }
    };
    return sinon.stub().returns(asyncIterable);
}

describe('v1alpha1.AnimeServiceClient', () => {
    it('has servicePath', () => {
        const servicePath = animeserviceModule.v1alpha1.AnimeServiceClient.servicePath;
        assert(servicePath);
    });

    it('has apiEndpoint', () => {
        const apiEndpoint = animeserviceModule.v1alpha1.AnimeServiceClient.apiEndpoint;
        assert(apiEndpoint);
    });

    it('has port', () => {
        const port = animeserviceModule.v1alpha1.AnimeServiceClient.port;
        assert(port);
        assert(typeof port === 'number');
    });

    it('should create a client with no option', () => {
        const client = new animeserviceModule.v1alpha1.AnimeServiceClient();
        assert(client);
    });

    it('should create a client with gRPC fallback', () => {
        const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
            fallback: true,
        });
        assert(client);
    });

    it('has initialize method and supports deferred initialization', async () => {
        const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        assert.strictEqual(client.animeServiceStub, undefined);
        await client.initialize();
        assert(client.animeServiceStub);
    });

    it('has close method', () => {
        const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        client.close();
    });

    it('has getProjectId method', async () => {
        const fakeProjectId = 'fake-project-id';
        const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
        const result = await client.getProjectId();
        assert.strictEqual(result, fakeProjectId);
        assert((client.auth.getProjectId as SinonStub).calledWithExactly());
    });

    it('has getProjectId method with callback', async () => {
        const fakeProjectId = 'fake-project-id';
        const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        client.auth.getProjectId = sinon.stub().callsArgWith(0, null, fakeProjectId);
        const promise = new Promise((resolve, reject) => {
            client.getProjectId((err?: Error|null, projectId?: string|null) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(projectId);
                }
            });
        });
        const result = await promise;
        assert.strictEqual(result, fakeProjectId);
    });

    describe('getAnime', () => {
        it('invokes getAnime without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GetAnimeRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime());
            client.innerApiCalls.getAnime = stubSimpleCall(expectedResponse);
            const [response] = await client.getAnime(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes getAnime without error using callback', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GetAnimeRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime());
            client.innerApiCalls.getAnime = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.getAnime(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IAnime|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes getAnime with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GetAnimeRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.getAnime = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.getAnime(request), expectedError);
            assert((client.innerApiCalls.getAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('createAnime', () => {
        it('invokes createAnime without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.CreateAnimeRequest());
            const expectedOptions = {otherArgs: {headers: {}}};;
            const expectedResponse = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime());
            client.innerApiCalls.createAnime = stubSimpleCall(expectedResponse);
            const [response] = await client.createAnime(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.createAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes createAnime without error using callback', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.CreateAnimeRequest());
            const expectedOptions = {otherArgs: {headers: {}}};;
            const expectedResponse = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime());
            client.innerApiCalls.createAnime = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.createAnime(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IAnime|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.createAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes createAnime with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.CreateAnimeRequest());
            const expectedOptions = {otherArgs: {headers: {}}};;
            const expectedError = new Error('expected');
            client.innerApiCalls.createAnime = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.createAnime(request), expectedError);
            assert((client.innerApiCalls.createAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('updateAnime', () => {
        it('invokes updateAnime without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.UpdateAnimeRequest());
            request.anime = {};
            request.anime.name = '';
            const expectedHeaderRequestParams = "anime.name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime());
            client.innerApiCalls.updateAnime = stubSimpleCall(expectedResponse);
            const [response] = await client.updateAnime(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.updateAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes updateAnime without error using callback', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.UpdateAnimeRequest());
            request.anime = {};
            request.anime.name = '';
            const expectedHeaderRequestParams = "anime.name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime());
            client.innerApiCalls.updateAnime = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.updateAnime(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IAnime|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.updateAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes updateAnime with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.UpdateAnimeRequest());
            request.anime = {};
            request.anime.name = '';
            const expectedHeaderRequestParams = "anime.name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.updateAnime = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.updateAnime(request), expectedError);
            assert((client.innerApiCalls.updateAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('deleteAnime', () => {
        it('invokes deleteAnime without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.DeleteAnimeRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.protobuf.Empty());
            client.innerApiCalls.deleteAnime = stubSimpleCall(expectedResponse);
            const [response] = await client.deleteAnime(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.deleteAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes deleteAnime without error using callback', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.DeleteAnimeRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.protobuf.Empty());
            client.innerApiCalls.deleteAnime = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.deleteAnime(
                    request,
                    (err?: Error|null, result?: protos.google.protobuf.IEmpty|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.deleteAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes deleteAnime with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.DeleteAnimeRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.deleteAnime = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.deleteAnime(request), expectedError);
            assert((client.innerApiCalls.deleteAnime as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('reconcileAnimes', () => {
        it('invokes reconcileAnimes without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ReconcileAnimesRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.longrunning.Operation());
            client.innerApiCalls.reconcileAnimes = stubLongRunningCall(expectedResponse);
            const [operation] = await client.reconcileAnimes(request);
            const [response] = await operation.promise();
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.reconcileAnimes as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes reconcileAnimes without error using callback', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ReconcileAnimesRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.longrunning.Operation());
            client.innerApiCalls.reconcileAnimes = stubLongRunningCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.reconcileAnimes(
                    request,
                    (err?: Error|null,
                     result?: LROperation<protos.animeshon.multimedia.v1alpha1.IReconcileAnimesResponse, protos.animeshon.multimedia.v1alpha1.IOperationMetadata>|null
                    ) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const operation = await promise as LROperation<protos.animeshon.multimedia.v1alpha1.IReconcileAnimesResponse, protos.animeshon.multimedia.v1alpha1.IOperationMetadata>;
            const [response] = await operation.promise();
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.reconcileAnimes as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes reconcileAnimes with call error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ReconcileAnimesRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.reconcileAnimes = stubLongRunningCall(undefined, expectedError);
            await assert.rejects(client.reconcileAnimes(request), expectedError);
            assert((client.innerApiCalls.reconcileAnimes as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes reconcileAnimes with LRO error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ReconcileAnimesRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.reconcileAnimes = stubLongRunningCall(undefined, undefined, expectedError);
            const [operation] = await client.reconcileAnimes(request);
            await assert.rejects(operation.promise(), expectedError);
            assert((client.innerApiCalls.reconcileAnimes as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes checkReconcileAnimesProgress without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const expectedResponse = generateSampleMessage(new operationsProtos.google.longrunning.Operation());
            expectedResponse.name = 'test';
            expectedResponse.response = {type_url: 'url', value: Buffer.from('')};
            expectedResponse.metadata = {type_url: 'url', value: Buffer.from('')}

            client.operationsClient.getOperation = stubSimpleCall(expectedResponse);
            const decodedOperation = await client.checkReconcileAnimesProgress(expectedResponse.name);
            assert.deepStrictEqual(decodedOperation.name, expectedResponse.name);
            assert(decodedOperation.metadata);
            assert((client.operationsClient.getOperation as SinonStub).getCall(0));
        });

        it('invokes checkReconcileAnimesProgress with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const expectedError = new Error('expected');

            client.operationsClient.getOperation = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.checkReconcileAnimesProgress(''), expectedError);
            assert((client.operationsClient.getOperation as SinonStub)
                .getCall(0));
        });
    });

    describe('listAnimes', () => {
        it('invokes listAnimes without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ListAnimesRequest());
            const expectedOptions = {otherArgs: {headers: {}}};;
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
            ];
            client.innerApiCalls.listAnimes = stubSimpleCall(expectedResponse);
            const [response] = await client.listAnimes(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.listAnimes as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes listAnimes without error using callback', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ListAnimesRequest());
            const expectedOptions = {otherArgs: {headers: {}}};;
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
            ];
            client.innerApiCalls.listAnimes = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.listAnimes(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IAnime[]|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.listAnimes as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes listAnimes with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ListAnimesRequest());
            const expectedOptions = {otherArgs: {headers: {}}};;
            const expectedError = new Error('expected');
            client.innerApiCalls.listAnimes = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.listAnimes(request), expectedError);
            assert((client.innerApiCalls.listAnimes as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes listAnimesStream without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ListAnimesRequest());
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
            ];
            client.descriptors.page.listAnimes.createStream = stubPageStreamingCall(expectedResponse);
            const stream = client.listAnimesStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.animeshon.multimedia.v1alpha1.Anime[] = [];
                stream.on('data', (response: protos.animeshon.multimedia.v1alpha1.Anime) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            const responses = await promise;
            assert.deepStrictEqual(responses, expectedResponse);
            assert((client.descriptors.page.listAnimes.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.listAnimes, request));
        });

        it('invokes listAnimesStream with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ListAnimesRequest());
            const expectedError = new Error('expected');
            client.descriptors.page.listAnimes.createStream = stubPageStreamingCall(undefined, expectedError);
            const stream = client.listAnimesStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.animeshon.multimedia.v1alpha1.Anime[] = [];
                stream.on('data', (response: protos.animeshon.multimedia.v1alpha1.Anime) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            await assert.rejects(promise, expectedError);
            assert((client.descriptors.page.listAnimes.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.listAnimes, request));
        });

        it('uses async iteration with listAnimes without error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ListAnimesRequest());
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.Anime()),
            ];
            client.descriptors.page.listAnimes.asyncIterate = stubAsyncIterationCall(expectedResponse);
            const responses: protos.animeshon.multimedia.v1alpha1.IAnime[] = [];
            const iterable = client.listAnimesAsync(request);
            for await (const resource of iterable) {
                responses.push(resource!);
            }
            assert.deepStrictEqual(responses, expectedResponse);
            assert.deepStrictEqual(
                (client.descriptors.page.listAnimes.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
        });

        it('uses async iteration with listAnimes with error', async () => {
            const client = new animeserviceModule.v1alpha1.AnimeServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.ListAnimesRequest());const expectedError = new Error('expected');
            client.descriptors.page.listAnimes.asyncIterate = stubAsyncIterationCall(undefined, expectedError);
            const iterable = client.listAnimesAsync(request);
            await assert.rejects(async () => {
                const responses: protos.animeshon.multimedia.v1alpha1.IAnime[] = [];
                for await (const resource of iterable) {
                    responses.push(resource!);
                }
            });
            assert.deepStrictEqual(
                (client.descriptors.page.listAnimes.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
        });
    });
});
