// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import {describe, it} from 'mocha';
import * as graphicnovelserviceModule from '../src';

import {PassThrough} from 'stream';

import {protobuf, LROperation, operationsProtos} from 'google-gax';

// Dynamically loaded proto JSON is needed to get the type information
// to fill in default values for request objects
const root = protobuf.Root.fromJSON(require('../protos/protos.json')).resolveAll();

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function getTypeDefaultValue(typeName: string, fields: string[]) {
    let type = root.lookupType(typeName) as protobuf.Type;
    for (const field of fields.slice(0, -1)) {
        type = type.fields[field]?.resolvedType as protobuf.Type;
    }
    return type.fields[fields[fields.length - 1]]?.defaultValue;
}

function generateSampleMessage<T extends object>(instance: T) {
    const filledObject = (instance.constructor as typeof protobuf.Message)
        .toObject(instance as protobuf.Message<T>, {defaults: true});
    return (instance.constructor as typeof protobuf.Message).fromObject(filledObject) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().rejects(error) : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().callsArgWith(2, error) : sinon.stub().callsArgWith(2, null, response);
}

function stubLongRunningCall<ResponseType>(response?: ResponseType, callError?: Error, lroError?: Error) {
    const innerStub = lroError ? sinon.stub().rejects(lroError) : sinon.stub().resolves([response]);
    const mockOperation = {
        promise: innerStub,
    };
    return callError ? sinon.stub().rejects(callError) : sinon.stub().resolves([mockOperation]);
}

function stubLongRunningCallWithCallback<ResponseType>(response?: ResponseType, callError?: Error, lroError?: Error) {
    const innerStub = lroError ? sinon.stub().rejects(lroError) : sinon.stub().resolves([response]);
    const mockOperation = {
        promise: innerStub,
    };
    return callError ? sinon.stub().callsArgWith(2, callError) : sinon.stub().callsArgWith(2, null, mockOperation);
}

function stubPageStreamingCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    const pagingStub = sinon.stub();
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
        }
    }
    const transformStub = error ? sinon.stub().callsArgWith(2, error) : pagingStub;
    const mockStream = new PassThrough({
        objectMode: true,
        transform: transformStub,
    });
    // trigger as many responses as needed
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            setImmediate(() => { mockStream.write({}); });
        }
        setImmediate(() => { mockStream.end(); });
    } else {
        setImmediate(() => { mockStream.write({}); });
        setImmediate(() => { mockStream.end(); });
    }
    return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    let counter = 0;
    const asyncIterable = {
        [Symbol.asyncIterator]() {
            return {
                async next() {
                    if (error) {
                        return Promise.reject(error);
                    }
                    if (counter >= responses!.length) {
                        return Promise.resolve({done: true, value: undefined});
                    }
                    return Promise.resolve({done: false, value: responses![counter++]});
                }
            };
        }
    };
    return sinon.stub().returns(asyncIterable);
}

describe('v1alpha1.GraphicNovelServiceClient', () => {
    describe('Common methods', () => {
        it('has servicePath', () => {
            const servicePath = graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient.servicePath;
            assert(servicePath);
        });

        it('has apiEndpoint', () => {
            const apiEndpoint = graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient.apiEndpoint;
            assert(apiEndpoint);
        });

        it('has port', () => {
            const port = graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient.port;
            assert(port);
            assert(typeof port === 'number');
        });

        it('should create a client with no option', () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient();
            assert(client);
        });

        it('should create a client with gRPC fallback', () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
                fallback: true,
            });
            assert(client);
        });

        it('has initialize method and supports deferred initialization', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            assert.strictEqual(client.graphicNovelServiceStub, undefined);
            await client.initialize();
            assert(client.graphicNovelServiceStub);
        });

        it('has close method for the initialized client', done => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            assert(client.graphicNovelServiceStub);
            client.close().then(() => {
                done();
            });
        });

        it('has close method for the non-initialized client', done => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            assert.strictEqual(client.graphicNovelServiceStub, undefined);
            client.close().then(() => {
                done();
            });
        });

        it('has getProjectId method', async () => {
            const fakeProjectId = 'fake-project-id';
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
            const result = await client.getProjectId();
            assert.strictEqual(result, fakeProjectId);
            assert((client.auth.getProjectId as SinonStub).calledWithExactly());
        });

        it('has getProjectId method with callback', async () => {
            const fakeProjectId = 'fake-project-id';
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.auth.getProjectId = sinon.stub().callsArgWith(0, null, fakeProjectId);
            const promise = new Promise((resolve, reject) => {
                client.getProjectId((err?: Error|null, projectId?: string|null) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(projectId);
                    }
                });
            });
            const result = await promise;
            assert.strictEqual(result, fakeProjectId);
        });
    });

    describe('getGraphicNovel', () => {
        it('invokes getGraphicNovel without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GraphicNovel()
            );
            client.innerApiCalls.getGraphicNovel = stubSimpleCall(expectedResponse);
            const [response] = await client.getGraphicNovel(request);
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.getGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.getGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes getGraphicNovel without error using callback', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GraphicNovel()
            );
            client.innerApiCalls.getGraphicNovel = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.getGraphicNovel(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IGraphicNovel|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.getGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.getGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes getGraphicNovel with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedError = new Error('expected');
            client.innerApiCalls.getGraphicNovel = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.getGraphicNovel(request), expectedError);
            const actualRequest = (client.innerApiCalls.getGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.getGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes getGraphicNovel with closed client', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.GetGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedError = new Error('The client has already been closed.');
            client.close();
            await assert.rejects(client.getGraphicNovel(request), expectedError);
        });
    });

    describe('createGraphicNovel', () => {
        it('invokes createGraphicNovel without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.CreateGraphicNovelRequest()
            );
            const expectedResponse = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GraphicNovel()
            );
            client.innerApiCalls.createGraphicNovel = stubSimpleCall(expectedResponse);
            const [response] = await client.createGraphicNovel(request);
            assert.deepStrictEqual(response, expectedResponse);
        });

        it('invokes createGraphicNovel without error using callback', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.CreateGraphicNovelRequest()
            );
            const expectedResponse = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GraphicNovel()
            );
            client.innerApiCalls.createGraphicNovel = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.createGraphicNovel(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IGraphicNovel|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
        });

        it('invokes createGraphicNovel with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.CreateGraphicNovelRequest()
            );
            const expectedError = new Error('expected');
            client.innerApiCalls.createGraphicNovel = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.createGraphicNovel(request), expectedError);
        });

        it('invokes createGraphicNovel with closed client', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.CreateGraphicNovelRequest()
            );
            const expectedError = new Error('The client has already been closed.');
            client.close();
            await assert.rejects(client.createGraphicNovel(request), expectedError);
        });
    });

    describe('updateGraphicNovel', () => {
        it('invokes updateGraphicNovel without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest()
            );
            request.graphicNovel ??= {};
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest', ['graphicNovel', 'name']);
            request.graphicNovel.name = defaultValue1;
            const expectedHeaderRequestParams = `graphic_novel.name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GraphicNovel()
            );
            client.innerApiCalls.updateGraphicNovel = stubSimpleCall(expectedResponse);
            const [response] = await client.updateGraphicNovel(request);
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.updateGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.updateGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes updateGraphicNovel without error using callback', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest()
            );
            request.graphicNovel ??= {};
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest', ['graphicNovel', 'name']);
            request.graphicNovel.name = defaultValue1;
            const expectedHeaderRequestParams = `graphic_novel.name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.GraphicNovel()
            );
            client.innerApiCalls.updateGraphicNovel = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.updateGraphicNovel(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IGraphicNovel|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.updateGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.updateGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes updateGraphicNovel with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest()
            );
            request.graphicNovel ??= {};
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest', ['graphicNovel', 'name']);
            request.graphicNovel.name = defaultValue1;
            const expectedHeaderRequestParams = `graphic_novel.name=${defaultValue1}`;
            const expectedError = new Error('expected');
            client.innerApiCalls.updateGraphicNovel = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.updateGraphicNovel(request), expectedError);
            const actualRequest = (client.innerApiCalls.updateGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.updateGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes updateGraphicNovel with closed client', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest()
            );
            request.graphicNovel ??= {};
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.UpdateGraphicNovelRequest', ['graphicNovel', 'name']);
            request.graphicNovel.name = defaultValue1;
            const expectedError = new Error('The client has already been closed.');
            client.close();
            await assert.rejects(client.updateGraphicNovel(request), expectedError);
        });
    });

    describe('deleteGraphicNovel', () => {
        it('invokes deleteGraphicNovel without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.google.protobuf.Empty()
            );
            client.innerApiCalls.deleteGraphicNovel = stubSimpleCall(expectedResponse);
            const [response] = await client.deleteGraphicNovel(request);
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.deleteGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.deleteGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes deleteGraphicNovel without error using callback', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.google.protobuf.Empty()
            );
            client.innerApiCalls.deleteGraphicNovel = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.deleteGraphicNovel(
                    request,
                    (err?: Error|null, result?: protos.google.protobuf.IEmpty|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.deleteGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.deleteGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes deleteGraphicNovel with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedError = new Error('expected');
            client.innerApiCalls.deleteGraphicNovel = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.deleteGraphicNovel(request), expectedError);
            const actualRequest = (client.innerApiCalls.deleteGraphicNovel as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.deleteGraphicNovel as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes deleteGraphicNovel with closed client', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.DeleteGraphicNovelRequest', ['name']);
            request.name = defaultValue1;
            const expectedError = new Error('The client has already been closed.');
            client.close();
            await assert.rejects(client.deleteGraphicNovel(request), expectedError);
        });
    });

    describe('reconcileGraphicNovels', () => {
        it('invokes reconcileGraphicNovels without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.google.longrunning.Operation()
            );
            client.innerApiCalls.reconcileGraphicNovels = stubLongRunningCall(expectedResponse);
            const [operation] = await client.reconcileGraphicNovels(request);
            const [response] = await operation.promise();
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes reconcileGraphicNovels without error using callback', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedResponse = generateSampleMessage(
              new protos.google.longrunning.Operation()
            );
            client.innerApiCalls.reconcileGraphicNovels = stubLongRunningCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.reconcileGraphicNovels(
                    request,
                    (err?: Error|null,
                     result?: LROperation<protos.animeshon.multimedia.v1alpha1.IReconcileGraphicNovelsResponse, protos.animeshon.multimedia.v1alpha1.IOperationMetadata>|null
                    ) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const operation = await promise as LROperation<protos.animeshon.multimedia.v1alpha1.IReconcileGraphicNovelsResponse, protos.animeshon.multimedia.v1alpha1.IOperationMetadata>;
            const [response] = await operation.promise();
            assert.deepStrictEqual(response, expectedResponse);
            const actualRequest = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes reconcileGraphicNovels with call error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedError = new Error('expected');
            client.innerApiCalls.reconcileGraphicNovels = stubLongRunningCall(undefined, expectedError);
            await assert.rejects(client.reconcileGraphicNovels(request), expectedError);
            const actualRequest = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes reconcileGraphicNovels with LRO error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest()
            );
            const defaultValue1 =
              getTypeDefaultValue('.animeshon.multimedia.v1alpha1.ReconcileGraphicNovelsRequest', ['name']);
            request.name = defaultValue1;
            const expectedHeaderRequestParams = `name=${defaultValue1}`;
            const expectedError = new Error('expected');
            client.innerApiCalls.reconcileGraphicNovels = stubLongRunningCall(undefined, undefined, expectedError);
            const [operation] = await client.reconcileGraphicNovels(request);
            await assert.rejects(operation.promise(), expectedError);
            const actualRequest = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[0];
            assert.deepStrictEqual(actualRequest, request);
            const actualHeaderRequestParams = (client.innerApiCalls.reconcileGraphicNovels as SinonStub)
                .getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
            assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
        });

        it('invokes checkReconcileGraphicNovelsProgress without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const expectedResponse = generateSampleMessage(
              new operationsProtos.google.longrunning.Operation()
            );
            expectedResponse.name = 'test';
            expectedResponse.response = {type_url: 'url', value: Buffer.from('')};
            expectedResponse.metadata = {type_url: 'url', value: Buffer.from('')}

            client.operationsClient.getOperation = stubSimpleCall(expectedResponse);
            const decodedOperation = await client.checkReconcileGraphicNovelsProgress(expectedResponse.name);
            assert.deepStrictEqual(decodedOperation.name, expectedResponse.name);
            assert(decodedOperation.metadata);
            assert((client.operationsClient.getOperation as SinonStub).getCall(0));
        });

        it('invokes checkReconcileGraphicNovelsProgress with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const expectedError = new Error('expected');

            client.operationsClient.getOperation = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.checkReconcileGraphicNovelsProgress(''), expectedError);
            assert((client.operationsClient.getOperation as SinonStub)
                .getCall(0));
        });
    });

    describe('listGraphicNovels', () => {
        it('invokes listGraphicNovels without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ListGraphicNovelsRequest()
            );const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
            ];
            client.innerApiCalls.listGraphicNovels = stubSimpleCall(expectedResponse);
            const [response] = await client.listGraphicNovels(request);
            assert.deepStrictEqual(response, expectedResponse);
        });

        it('invokes listGraphicNovels without error using callback', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ListGraphicNovelsRequest()
            );const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
            ];
            client.innerApiCalls.listGraphicNovels = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.listGraphicNovels(
                    request,
                    (err?: Error|null, result?: protos.animeshon.multimedia.v1alpha1.IGraphicNovel[]|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
        });

        it('invokes listGraphicNovels with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ListGraphicNovelsRequest()
            );
            const expectedError = new Error('expected');
            client.innerApiCalls.listGraphicNovels = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.listGraphicNovels(request), expectedError);
        });

        it('invokes listGraphicNovelsStream without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ListGraphicNovelsRequest()
            );
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
            ];
            client.descriptors.page.listGraphicNovels.createStream = stubPageStreamingCall(expectedResponse);
            const stream = client.listGraphicNovelsStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.animeshon.multimedia.v1alpha1.GraphicNovel[] = [];
                stream.on('data', (response: protos.animeshon.multimedia.v1alpha1.GraphicNovel) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            const responses = await promise;
            assert.deepStrictEqual(responses, expectedResponse);
            assert((client.descriptors.page.listGraphicNovels.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.listGraphicNovels, request));
        });

        it('invokes listGraphicNovelsStream with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ListGraphicNovelsRequest()
            );
            const expectedError = new Error('expected');
            client.descriptors.page.listGraphicNovels.createStream = stubPageStreamingCall(undefined, expectedError);
            const stream = client.listGraphicNovelsStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.animeshon.multimedia.v1alpha1.GraphicNovel[] = [];
                stream.on('data', (response: protos.animeshon.multimedia.v1alpha1.GraphicNovel) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            await assert.rejects(promise, expectedError);
            assert((client.descriptors.page.listGraphicNovels.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.listGraphicNovels, request));
        });

        it('uses async iteration with listGraphicNovels without error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ListGraphicNovelsRequest()
            );
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
              generateSampleMessage(new protos.animeshon.multimedia.v1alpha1.GraphicNovel()),
            ];
            client.descriptors.page.listGraphicNovels.asyncIterate = stubAsyncIterationCall(expectedResponse);
            const responses: protos.animeshon.multimedia.v1alpha1.IGraphicNovel[] = [];
            const iterable = client.listGraphicNovelsAsync(request);
            for await (const resource of iterable) {
                responses.push(resource!);
            }
            assert.deepStrictEqual(responses, expectedResponse);
            assert.deepStrictEqual(
                (client.descriptors.page.listGraphicNovels.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
        });

        it('uses async iteration with listGraphicNovels with error', async () => {
            const client = new graphicnovelserviceModule.v1alpha1.GraphicNovelServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(
              new protos.animeshon.multimedia.v1alpha1.ListGraphicNovelsRequest()
            );
            const expectedError = new Error('expected');
            client.descriptors.page.listGraphicNovels.asyncIterate = stubAsyncIterationCall(undefined, expectedError);
            const iterable = client.listGraphicNovelsAsync(request);
            await assert.rejects(async () => {
                const responses: protos.animeshon.multimedia.v1alpha1.IGraphicNovel[] = [];
                for await (const resource of iterable) {
                    responses.push(resource!);
                }
            });
            assert.deepStrictEqual(
                (client.descriptors.page.listGraphicNovels.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
        });
    });
});
