name: release-please

on:
  push:
    branches: [master]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          command: manifest
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
