// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import { describe, it } from 'mocha';
import * as imageModule from '../src';

import {PassThrough} from 'stream';

import {protobuf} from 'google-gax';

function generateSampleMessage<T extends object>(instance: T) {
    const filledObject = (instance.constructor as typeof protobuf.Message)
        .toObject(instance as protobuf.Message<T>, {defaults: true});
    return (instance.constructor as typeof protobuf.Message).fromObject(filledObject) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().rejects(error) : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().callsArgWith(2, error) : sinon.stub().callsArgWith(2, null, response);
}

function stubPageStreamingCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    const pagingStub = sinon.stub();
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
        }
    }
    const transformStub = error ? sinon.stub().callsArgWith(2, error) : pagingStub;
    const mockStream = new PassThrough({
        objectMode: true,
        transform: transformStub,
    });
    // trigger as many responses as needed
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            setImmediate(() => { mockStream.write({}); });
        }
        setImmediate(() => { mockStream.end(); });
    } else {
        setImmediate(() => { mockStream.write({}); });
        setImmediate(() => { mockStream.end(); });
    }
    return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    let counter = 0;
    const asyncIterable = {
        [Symbol.asyncIterator]() {
            return {
                async next() {
                    if (error) {
                        return Promise.reject(error);
                    }
                    if (counter >= responses!.length) {
                        return Promise.resolve({done: true, value: undefined});
                    }
                    return Promise.resolve({done: false, value: responses![counter++]});
                }
            };
        }
    };
    return sinon.stub().returns(asyncIterable);
}

describe('v1alpha1.ImageClient', () => {
    it('has servicePath', () => {
        const servicePath = imageModule.v1alpha1.ImageClient.servicePath;
        assert(servicePath);
    });

    it('has apiEndpoint', () => {
        const apiEndpoint = imageModule.v1alpha1.ImageClient.apiEndpoint;
        assert(apiEndpoint);
    });

    it('has port', () => {
        const port = imageModule.v1alpha1.ImageClient.port;
        assert(port);
        assert(typeof port === 'number');
    });

    it('should create a client with no option', () => {
        const client = new imageModule.v1alpha1.ImageClient();
        assert(client);
    });

    it('should create a client with gRPC fallback', () => {
        const client = new imageModule.v1alpha1.ImageClient({
            fallback: true,
        });
        assert(client);
    });

    it('has initialize method and supports deferred initialization', async () => {
        const client = new imageModule.v1alpha1.ImageClient({
            credentials: { client_email: 'bogus', private_key: 'bogus' },
            projectId: 'bogus',
        });
        assert.strictEqual(client.imageStub, undefined);
        await client.initialize();
        assert(client.imageStub);
    });

    it('has close method', () => {
        const client = new imageModule.v1alpha1.ImageClient({
            credentials: { client_email: 'bogus', private_key: 'bogus' },
            projectId: 'bogus',
        });
        client.close();
    });

    it('has getProjectId method', async () => {
        const fakeProjectId = 'fake-project-id';
        const client = new imageModule.v1alpha1.ImageClient({
            credentials: { client_email: 'bogus', private_key: 'bogus' },
            projectId: 'bogus',
        });
        client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
        const result = await client.getProjectId();
        assert.strictEqual(result, fakeProjectId);
        assert((client.auth.getProjectId as SinonStub).calledWithExactly());
    });

    it('has getProjectId method with callback', async () => {
        const fakeProjectId = 'fake-project-id';
        const client = new imageModule.v1alpha1.ImageClient({
            credentials: { client_email: 'bogus', private_key: 'bogus' },
            projectId: 'bogus',
        });
        client.auth.getProjectId = sinon.stub().callsArgWith(0, null, fakeProjectId);
        const promise = new Promise((resolve, reject) => {
            client.getProjectId((err?: Error|null, projectId?: string|null) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(projectId);
                }
            });
        });
        const result = await promise;
        assert.strictEqual(result, fakeProjectId);
    });

    describe('uploadImage', () => {
        it('invokes uploadImage without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.UploadImageRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.UploadImageResponse());
            client.innerApiCalls.uploadImage = stubSimpleCall(expectedResponse);
            const [response] = await client.uploadImage(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.uploadImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes uploadImage without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.UploadImageRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.UploadImageResponse());
            client.innerApiCalls.uploadImage = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.uploadImage(
                    request,
                    (err?: Error|null, result?: protos.animeshon.image.v1alpha1.IUploadImageResponse|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.uploadImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes uploadImage with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.UploadImageRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.uploadImage = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.uploadImage(request), expectedError);
            assert((client.innerApiCalls.uploadImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('importImage', () => {
        it('invokes importImage without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ImportImageRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.ImportImageResponse());
            client.innerApiCalls.importImage = stubSimpleCall(expectedResponse);
            const [response] = await client.importImage(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.importImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes importImage without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ImportImageRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.ImportImageResponse());
            client.innerApiCalls.importImage = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.importImage(
                    request,
                    (err?: Error|null, result?: protos.animeshon.image.v1alpha1.IImportImageResponse|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.importImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes importImage with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ImportImageRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.importImage = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.importImage(request), expectedError);
            assert((client.innerApiCalls.importImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('getImage', () => {
        it('invokes getImage without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetImageRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.api.HttpBody());
            client.innerApiCalls.getImage = stubSimpleCall(expectedResponse);
            const [response] = await client.getImage(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes getImage without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetImageRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.api.HttpBody());
            client.innerApiCalls.getImage = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.getImage(
                    request,
                    (err?: Error|null, result?: protos.google.api.IHttpBody|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes getImage with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetImageRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.getImage = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.getImage(request), expectedError);
            assert((client.innerApiCalls.getImage as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('getAlbum', () => {
        it('invokes getAlbum without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetAlbumRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.Album());
            client.innerApiCalls.getAlbum = stubSimpleCall(expectedResponse);
            const [response] = await client.getAlbum(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes getAlbum without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetAlbumRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.Album());
            client.innerApiCalls.getAlbum = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.getAlbum(
                    request,
                    (err?: Error|null, result?: protos.animeshon.image.v1alpha1.IAlbum|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes getAlbum with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetAlbumRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.getAlbum = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.getAlbum(request), expectedError);
            assert((client.innerApiCalls.getAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('createAlbum', () => {
        it('invokes createAlbum without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.CreateAlbumRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.Album());
            client.innerApiCalls.createAlbum = stubSimpleCall(expectedResponse);
            const [response] = await client.createAlbum(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.createAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes createAlbum without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.CreateAlbumRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.Album());
            client.innerApiCalls.createAlbum = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.createAlbum(
                    request,
                    (err?: Error|null, result?: protos.animeshon.image.v1alpha1.IAlbum|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.createAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes createAlbum with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.CreateAlbumRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.createAlbum = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.createAlbum(request), expectedError);
            assert((client.innerApiCalls.createAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('deleteAlbum', () => {
        it('invokes deleteAlbum without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.DeleteAlbumRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.protobuf.Empty());
            client.innerApiCalls.deleteAlbum = stubSimpleCall(expectedResponse);
            const [response] = await client.deleteAlbum(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.deleteAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes deleteAlbum without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.DeleteAlbumRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.protobuf.Empty());
            client.innerApiCalls.deleteAlbum = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.deleteAlbum(
                    request,
                    (err?: Error|null, result?: protos.google.protobuf.IEmpty|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.deleteAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes deleteAlbum with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.DeleteAlbumRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.deleteAlbum = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.deleteAlbum(request), expectedError);
            assert((client.innerApiCalls.deleteAlbum as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('getAlbumSettings', () => {
        it('invokes getAlbumSettings without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetAlbumSettingsRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.AlbumSettings());
            client.innerApiCalls.getAlbumSettings = stubSimpleCall(expectedResponse);
            const [response] = await client.getAlbumSettings(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getAlbumSettings as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes getAlbumSettings without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetAlbumSettingsRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.AlbumSettings());
            client.innerApiCalls.getAlbumSettings = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.getAlbumSettings(
                    request,
                    (err?: Error|null, result?: protos.animeshon.image.v1alpha1.IAlbumSettings|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getAlbumSettings as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes getAlbumSettings with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.GetAlbumSettingsRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.getAlbumSettings = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.getAlbumSettings(request), expectedError);
            assert((client.innerApiCalls.getAlbumSettings as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('updateAlbumSettings', () => {
        it('invokes updateAlbumSettings without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.UpdateAlbumSettingsRequest());
            request.settings = {};
            request.settings.name = '';
            const expectedHeaderRequestParams = "settings.name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.AlbumSettings());
            client.innerApiCalls.updateAlbumSettings = stubSimpleCall(expectedResponse);
            const [response] = await client.updateAlbumSettings(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.updateAlbumSettings as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes updateAlbumSettings without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.UpdateAlbumSettingsRequest());
            request.settings = {};
            request.settings.name = '';
            const expectedHeaderRequestParams = "settings.name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.animeshon.image.v1alpha1.AlbumSettings());
            client.innerApiCalls.updateAlbumSettings = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.updateAlbumSettings(
                    request,
                    (err?: Error|null, result?: protos.animeshon.image.v1alpha1.IAlbumSettings|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.updateAlbumSettings as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes updateAlbumSettings with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.UpdateAlbumSettingsRequest());
            request.settings = {};
            request.settings.name = '';
            const expectedHeaderRequestParams = "settings.name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.updateAlbumSettings = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.updateAlbumSettings(request), expectedError);
            assert((client.innerApiCalls.updateAlbumSettings as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('listAlbums', () => {
        it('invokes listAlbums without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ListAlbumsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
            ];
            client.innerApiCalls.listAlbums = stubSimpleCall(expectedResponse);
            const [response] = await client.listAlbums(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.listAlbums as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes listAlbums without error using callback', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ListAlbumsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
            ];
            client.innerApiCalls.listAlbums = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.listAlbums(
                    request,
                    (err?: Error|null, result?: protos.animeshon.image.v1alpha1.IAlbum[]|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.listAlbums as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes listAlbums with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ListAlbumsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.listAlbums = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.listAlbums(request), expectedError);
            assert((client.innerApiCalls.listAlbums as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes listAlbumsStream without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ListAlbumsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedResponse = [
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
            ];
            client.descriptors.page.listAlbums.createStream = stubPageStreamingCall(expectedResponse);
            const stream = client.listAlbumsStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.animeshon.image.v1alpha1.Album[] = [];
                stream.on('data', (response: protos.animeshon.image.v1alpha1.Album) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            const responses = await promise;
            assert.deepStrictEqual(responses, expectedResponse);
            assert((client.descriptors.page.listAlbums.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.listAlbums, request));
            assert.strictEqual(
                (client.descriptors.page.listAlbums.createStream as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });

        it('invokes listAlbumsStream with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ListAlbumsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedError = new Error('expected');
            client.descriptors.page.listAlbums.createStream = stubPageStreamingCall(undefined, expectedError);
            const stream = client.listAlbumsStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.animeshon.image.v1alpha1.Album[] = [];
                stream.on('data', (response: protos.animeshon.image.v1alpha1.Album) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            await assert.rejects(promise, expectedError);
            assert((client.descriptors.page.listAlbums.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.listAlbums, request));
            assert.strictEqual(
                (client.descriptors.page.listAlbums.createStream as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });

        it('uses async iteration with listAlbums without error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ListAlbumsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";const expectedResponse = [
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
              generateSampleMessage(new protos.animeshon.image.v1alpha1.Album()),
            ];
            client.descriptors.page.listAlbums.asyncIterate = stubAsyncIterationCall(expectedResponse);
            const responses: protos.animeshon.image.v1alpha1.IAlbum[] = [];
            const iterable = client.listAlbumsAsync(request);
            for await (const resource of iterable) {
                responses.push(resource!);
            }
            assert.deepStrictEqual(responses, expectedResponse);
            assert.deepStrictEqual(
                (client.descriptors.page.listAlbums.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
            assert.strictEqual(
                (client.descriptors.page.listAlbums.asyncIterate as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });

        it('uses async iteration with listAlbums with error', async () => {
            const client = new imageModule.v1alpha1.ImageClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.animeshon.image.v1alpha1.ListAlbumsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";const expectedError = new Error('expected');
            client.descriptors.page.listAlbums.asyncIterate = stubAsyncIterationCall(undefined, expectedError);
            const iterable = client.listAlbumsAsync(request);
            await assert.rejects(async () => {
                const responses: protos.animeshon.image.v1alpha1.IAlbum[] = [];
                for await (const resource of iterable) {
                    responses.push(resource!);
                }
            });
            assert.deepStrictEqual(
                (client.descriptors.page.listAlbums.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
            assert.strictEqual(
                (client.descriptors.page.listAlbums.asyncIterate as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });
    });
});
